Fix locked array error on texture cleanup
ao-org/argentum-online-client pull request #388
Opened 2024-11-13 04:01 UTC by adrianbielsa1

Issue relacionado: https://github.com/ao-org/argentum-online-server/issues/578.

En los logs podemos ver que uno de los problemas es que se intenta modificar el array mientras está en uso; esto es porque los bloques `With` toman una referencia del arreglo (en este caso `surfaceEntry`), el cual más adelante (en `RemoveLRU`) estamos intentando redimensionar.

Por otro lado, no hay ninguna razón para usar `D3DPOOL_DEFAULT` en lugar de `D3DPOOL_MANAGED` ([referencia](https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3dpool)), así que lo cambié en los lugares que se estaba usando.

2024-11-13 04:03 UTC, ao-20 commented
Fellow citizen of Nix, one of the admins verify this pull request

2024-11-17 22:14 UTC, morgolock requested changes

2024-11-17 22:14 UTC, morgolock commented on CODIGO/clsTexManager.cls
> +    Set Texture = mD3D.CreateTextureFromFileInMemoryEx(device, Bytes(0), UBound(Bytes) + 1, Width, Height, 1, 0, D3DFMT_A8R8G8B8, D3DPOOL_MANAGED, D3DX_FILTER_LINEAR, D3DX_FILTER_LINEAR, &HFF000000,
Hay que primero llamar `mD3D.CreateTextureFromFileInMemoryEx( ... D3DPOOL_DEFAULT)`

y si eso falla llamar con `mD3D.CreateTextureFromFileInMemoryEx( ... D3DPOOL_MANAGED)`

2024-11-18 01:33 UTC, adrianbielsa1 commented on CODIGO/clsTexManager.cls
> +    Set Texture = mD3D.CreateTextureFromFileInMemoryEx(device, Bytes(0), UBound(Bytes) + 1, Width, Height, 1, 0, D3DFMT_A8R8G8B8, D3DPOOL_MANAGED, D3DX_FILTER_LINEAR, D3DX_FILTER_LINEAR, &HFF000000,
@morgolock cuál sería el razonamiento de esta sugerencia?

2024-11-18 13:52 UTC, morgolock commented on CODIGO/clsTexManager.cls
> +    Set Texture = mD3D.CreateTextureFromFileInMemoryEx(device, Bytes(0), UBound(Bytes) + 1, Width, Height, 1, 0, D3DFMT_A8R8G8B8, D3DPOOL_MANAGED, D3DX_FILTER_LINEAR, D3DX_FILTER_LINEAR, &HFF000000,
La idea es cargar la textura en la memoria de video usando DEFAULT. Si cambias a MANAGED como hiciste la textura no necesariamente usa memoria de video.

> Resources are placed in theResources are placed in the memory pool most appropriate for the set of usages requested for the given resource. This is usually video memory, including both local video memory and AGP memory.  memory pool most appropriate for the set of usages requested for the given resource. This is usually video memory, including both local video memory and AGP memory. 

Por eso lo mejor es algo asi:

```
Set Texture = mD3D.CreateTextureFromFileInMemoryEx(device, Bytes(0), UBound(Bytes) + 1, Width, Height, 1, 0, D3DFMT_A8R8G8B8, D3DPOOL_DEFAULT, D3DX_FILTER_LINEAR, D3DX_FILTER_LINEAR, &HFF000000, ByVal 0, ByVal 0)

If Texture is nothing then ' Fallo la carga en memoria de video
et Texture = mD3D.CreateTextureFromFileInMemoryEx(device, Bytes(0), UBound(Bytes) + 1, Width, Height, 1, 0, D3DFMT_A8R8G8B8, D3DPOOL_MANAGED, D3DX_FILTER_LINEAR, D3DX_FILTER_LINEAR, &HFF000000, ByVal 0, ByVal 0)
endif
```

2024-11-19 03:20 UTC, adrianbielsa1 commented on CODIGO/clsTexManager.cls
> +    Set Texture = mD3D.CreateTextureFromFileInMemoryEx(device, Bytes(0), UBound(Bytes) + 1, Width, Height, 1, 0, D3DFMT_A8R8G8B8, D3DPOOL_MANAGED, D3DX_FILTER_LINEAR, D3DX_FILTER_LINEAR, &HFF000000,
Lo que pasa es que al hacer eso, tenés que manejar manualmente el tema de [lost devices](https://learn.microsoft.com/en-us/windows/win32/direct3d9/lost-devices) (por ej. cuando el usuario alt-tabea, o la computadora se bloquea por inactividad). Usando `D3DPOOL_MANAGED` esto no pasa porque DirectX crea la textura en RAM y se copia a VRAM [según sea necesario](https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3dpool):
> Resources are copied automatically to device-accessible memory as needed. Managed resources are backed by system memory and do not need to be recreated when a device is lost.

Yo, honestamente, no veo razón para usar `D3DPOOL_DEFAULT` en vez de `D3DPOOL_MANAGED` en este caso particular; principalmente porque:
* Tener que detectar cuando se da un "lost device" (y recrear los recursos necesarios) es código que hay que armar, que no estoy seguro si está presente hoy.
* No veo tampoco un excesivo consumo de memoria ya que AO internamente va midiendo la memoria en uso e intenta liberar cuando hay problemas o cuando se llega al límite (esto último estoy hablando de memoria, pero recuerdo que algunos lo hacen así).
* En tema performance dudo MUCHO de que sea una diferencia notable.

Si aún bajo esos argumentos te parece mejor usar `D3DPOOL_DEFAULT`, no hay problema, lo cambiamos. Sumo además que la función en la que lo cambié (`CreateTextureFromData`) no se está usando, es código muerto. La que se usa es `LoadTexture`, que siempre estuvo usando `D3DPOOL_MANAGED`:

```
Private Function LoadTexture(ByVal FileName As String, ByRef Dest As Direct3DTexture8) As Long
On Error GoTo LoadTexture_ErrHandler
    Dim bytArr()     As Byte
    #If Compresion = 1 Then
        If Not Extract_File_To_Memory(Graphics, App.path & "\..\Recursos\OUTPUT\", LTrim(FileName) & ".png", bytArr, ResourcesPassword) Then
            Debug.Print "�No se puede cargar el grafico numero " & FileName & "!"
            Exit Function
        End If
        Set Dest = mD3D.CreateTextureFromFileInMemoryEx(device, bytArr(0), UBound(bytArr) + 1, D3DX_DEFAULT, D3DX_DEFAULT, 1, 0, _
                                                            D3DFMT_A8R8G8B8, D3DPOOL_MANAGED, D3DX_FILTER_LINEAR, D3DX_FILTER_LINEAR, &HFF000000, ByVal 0, ByVal 0)
    #Else
        Dim PathToFile As String
        PathToFile = App.path & "\..\Recursos\Graficos\" & LTrim(FileName) & ".png"
        If Not FileExist(PathToFile, vbArchive) Then
            Debug.Print "�No se puede cargar el grafico numero " & PathToFile & "!"
            Exit Function
        End If

        Set Dest = mD3D.CreateTextureFromFileEx(device, PathToFile, 0, 0, _
             1, 0, D3DFMT_A8R8G8B8, D3DPOOL_MANAGED, D3DX_FILTER_LINEAR, D3DX_FILTER_LINEAR, &HFF000000, ByVal 0, ByVal 0)
    #End If
    Exit Function
LoadTexture_ErrHandler:
    LoadTexture = Err.Number
End Function
```

2024-11-19 19:29 UTC, RecoX commented
Una cosa que habria que hacer es limpiar el Pull Request ya que rompe muchos caracteres y hay muchos cambios innecesarios alrededor de todo el proyecto.

La mas facil ahora en mi opinion es arrancar de cero desde `master`, agregar todos los cambios necesarios y antes de hacer un commit ejecutar el archivo `git_ignore_case.sh` y luego verificar con git difftool (puede ser cualquier otro programa como WinMege, Meld o Github Desktop)

Con eso nos aseguramos de meter solo los cambios que queremos sin romper caracteres y reducir la cantidad de cambios en el PR.

2024-11-20 04:56 UTC, adrianbielsa1 commented
@morgolock @RecoX Ahí corregí algunos de los caracteres que habían quedado raros, sumé las sugerencias de Pablo, y dejé un poquito más limpio el diff. Se ve que aún corriendo `git_ignore_case.sh` se ve que al proyecto no le gusta mucho que lo abra con VSCode, pero me parece que el cambio está mucho más visible ahora.

2024-11-20 18:50 UTC, morgolock requested changes

2024-11-20 18:50 UTC, morgolock commented on CODIGO/clsTexManager.cls
> +
Podes al principio de la funcion poner `Set Dest = nothing` por favor? Onda inicializar la variable

2024-11-20 18:50 UTC, morgolock commented on CODIGO/clsTexManager.cls
> +
Inicializar CreateDirect3dTexture = nothing

2024-11-20 18:50 UTC, morgolock commented on CODIGO/clsTexManager.cls
> +
Y tambien LoadTexture = 0

2024-11-20 18:50 UTC, morgolock commented on CODIGO/clsTexManager.cls
> +    If (loadResult = E_OUTOFMEMORY) Or (loadResult = D3DERR_OUTOFVIDEOMEMORY) Then
Estos ifs aca estan medio confusos y no pregunta por todos los codigos de error que `CreateTextureFromFileEx` puede devolver.

Te sugiero que preguntes que reemplaces el if por un select y controles todos los errores

```
if (loadResult <> 0) then
       select loadResult
              case D3DERR_INVALIDCALL ... log error (INVALIDCALL)
              case D3DERR_NOTAVAILABLE ..
              case D3DERR_OUTOFVIDEOMEMORY ..
              case D3DXERR_INVALIDDATA ...
              case OUTOFMEMORY ...
                          Dim i As Long
                          For i = 0 To 100
                              Call RemoveLRU
                          Next
                  
                          'Try to load the texture again, if it fails we've run out of
                          'options.
                          loadResult = LoadTexture(str(FileNum), Texture)
```

2024-11-20 18:50 UTC, morgolock commented on CODIGO/clsTexManager.cls
> +    If (loadResult = E_OUTOFMEMORY) Or (loadResult = D3DERR_OUTOFVIDEOMEMORY) Then
Basicamente reemplazar lineas 213 a 231 por lo sugerido ariba

2024-11-28 01:58 UTC, RecoX approved these changes

2024-11-28 02:00 UTC, merged