i18n support
ao-org/argentum-online-client pull request #392
Opened 2024-11-27 10:56 UTC by RecoX

This pull request introduces several changes to improve the localization functionality of the project, including adding support for JSON-based language files and updating the code to use these files. The most important changes include the addition of new JSON language files, modifications to handle localization settings, and updates to use JSON-based messages.

Localization improvements:

* Added new JSON language files for English and Spanish with localization messages (`Languages/1.json`, `Languages/english.json`, `Languages/spanish.json`). [[1]](diffhunk://#diff-c095816dc41d76343121e4679e7617b5f474b5b2549e82ac564ad70f21e49274R1-R3) [[2]](diffhunk://#diff-03b15982ff5fabf886db90a3511cfd94f63a32128078943cd243a73415bd60d0R1-R3)
* Updated `SetLanguageApplication` function to handle localization settings, load the appropriate JSON language file, and parse its content (`CODIGO/ModLanguage.bas`).
* Introduced a new function `DirLanguage` to return the path to the language files directory (`CODIGO/General.bas`).

Code updates to use JSON-based messages:

* Replaced hardcoded message `MENSAJE_CRIATURA_MATADO` with its JSON-based equivalent in `HandleNPCKillUser` (`CODIGO/Protocol.bas`).
* Added a new module reference for JSON handling (`Argentum20.vbp`).

2024-11-27 22:13 UTC, morgolock requested changes

2024-11-27 22:13 UTC, morgolock commented on CODIGO/General.bas
> +Public Function DirLanguage() As String
Mover esta funcion  a CODIGO/ModLanguage.bas asi tenemos todo lo de localizacion en un unico modulo

2024-11-27 22:13 UTC, morgolock commented on Argentum20.vbp
> +Reference=*\G{420B2830-E718-11CF-893D-00A0C9054228}#1.0#0
Que es esto? Una referencia a un control? Podemos eliminar los cambios en lineas 6 y 7 ?

2024-11-27 22:15 UTC, RecoX commented on Argentum20.vbp
> +Reference=*\G{420B2830-E718-11CF-893D-00A0C9054228}#1.0#0
Son estas 2 librerias

Microsoft ActiveX Data Objects 2.5 Library aca no recuerdo que utiliza

Microsoft Scripting Runtime de aca utiliza el type Dictionary

Son necesarias para poder hacer andar JSON.bas

2024-12-03 21:15 UTC, morgolock approved these changes

2024-12-03 21:18 UTC, RecoX commented on Languages/1.json
> +  "LOGIN_SCREEN_WELCOME_MESSAGE": "Â¡Bienvenido de nuevo! Â¡Disfruta tu viaje por Argentum Online!"
Hay caracteres rotos

2024-12-03 21:23 UTC, morgolock commented on Languages/1.json
> +  "LOGIN_SCREEN_WELCOME_MESSAGE": "Â¡Bienvenido de nuevo! Â¡Disfruta tu viaje por Argentum Online!"
Arreglado en el ultimo parche

2024-12-03 22:08 UTC, morgolock approved these changes

2024-12-03 23:52 UTC, merged