Ocultar MS
ao-org/argentum-online-client pull request #401
Opened 2024-12-07 13:02 UTC by plusin

Hace mucho tiempo se ha desactivado la opción de PING del servidor, por sugerencia de @ccmercuri subo PR para que no muestre más el texto MS.

2024-12-07 21:07 UTC, RecoX commented on CODIGO/engine.bas
> +    'frmMain.ms.Caption = PingRender & "ms"
Eliminar linea en ves de comentarla ya que se elimino su funcionalidad.

2024-12-08 00:32 UTC, plusin commented on CODIGO/engine.bas
> +    'frmMain.ms.Caption = PingRender & "ms"
Hecho.

2024-12-08 20:25 UTC, morgolock requested changes

2024-12-08 20:25 UTC, morgolock commented on CODIGO/frmMain.frm
Por favor revertir los cambios en este file. No hace falta tocar el frm.

2024-12-08 20:27 UTC, morgolock commented on CODIGO/engine.bas
> +    'frmMain.ms.Caption = PingRender & "ms"
Por favor en el titutlo pone una descripcion completa, `ocultar el label que informa ping en ms en el frmMain.frm`

2024-12-08 20:30 UTC, morgolock requested changes
Por favor en el titutlo pone una descripcion completa, ocultar el label que informa ping en ms en el frmMain.frm

2024-12-09 20:16 UTC, morgolock approved these changes

2024-12-10 19:52 UTC, RecoX approved these changes

2024-12-10 19:52 UTC, merged